### ISSUE TITLE
Move clone data all into the `clones` object

### ISSUE THREAD

**Issue by meganrm** [allen-cell-animated/cell-catalog#106]
## What needs to happen?
in addition to `type`, `clone_number`, and `transfection_replicate`, 
clones should have 
1. positive_cells        
```YAML
 {
                            label: "Troponin T, % Positive Cells(n)",
                            name: "positive_cells",
                            widget: "float",
                            required: false,
}
```
 (see #105 )

2. `antibody_analysis`, multiselect list: PAX6, SOX17, Brachyury. (I can't remember if you can let the user add new ones, if so, allow that) 
```YAML
 {
                            label: "Passing Antibodies",
                            name: "antibody_analysis",
                            hint: "select all antibodies this clone passed ",
                           widget: "select",
                            options: [PAX6, SOX17, Brachyury],
                    multiple: true,

}
```
4. differentiation: list of objects, with each of the transcription factors as the key, and the value a float. (see the design)

remove `stem_cell_characteristics`
move all the `positive_cells` into these new data formats in each of the index.md files
